[package]
name = "sip2-mediator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
syslog = "6.0"
uuid = { version = "1", features = ["v4"] }
serde_json = "1"
serde_urlencoded = "0.7"
reqwest = { version = "0.11.10", features = ["blocking"] }
#sip2 = { version = "0.2", features = ["json"] }
sip2 = { version = "0.2", features = ["json"], path = "../sip2-client-rs" }
getopts = "0.2"
threadpool = "1.8"
