[package]
name = "sip2-mediator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.9"
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
reqwest = { version = "0.11.10", features = ["blocking"] }
sip2 = { version = "0.2", features = ["json"] }
