[package]
name = "sip2-mediator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
serde_json = "1.0.81"
openssl = "0.10.40"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11.10", features = ["json"] }
sip2 = "0.1.2"
